using System.Collections.Generic;

namespace SpellTyper.Scripts;

public class Data {
  private static Data instance = null;

  private Data() {
    Spells.Sort((a, b) => a.Length.CompareTo(b.Length));
  }

  public static Data Instance {
    get { return instance ??= new Data(); }
  }
  
  public List<string> Spells { get; private set; } = [
    "Alohomora",
    "Serpensortia",
    "Skurge",
    "Steleus",
    "Ventus",
    "Verdimillious",
    "Waddiwasi",
    "Tergeo",
    "Titillando",
    "Tentaclifors",
    "Stupefy",
    "Salvio",
    "Hexia",
    "Riddikulus",
    "Repello",
    "Inimicum",
    "Rictusempra",
    "Relashio",
    "Reducto",
    "Redactum",
    "Quietus",
    "Protego",
    "Portus",
    "Petrificus",
    "Peskipiksi",
    "Pesternomi",
    "Temporus",
    "Periculum",
    "Orbis",
    "Orchideous",
    "Obscuro",
    "Obliviate",
    "Nox",
    "Muffliato",
    "Morsmordre",
    "Mobilicorpus",
    "Mobiliarbus",
    "Mimblewimble",
    "Meteolojinx",
    "Melofors",
    "Liberacorpus",
    "Legilimens",
    "Langlock",
    "Lacarnum",
    "Kineto",
    "Inflatus",
    "Informous",
    "Incendio",
    "Inanimatus",
    "Imperio",
    "Immobulus",
    "Keitch",
    "Homenum",
    "Harmonia",
    "Herbivicus",
    "Glisseo",
    "Glacius",
    "Geminio",
    "Furnunculus",
    "Fumos",
    "Flipendo",
    "Flagrate",
    "Fiendfyre",
    "Fianto",
    "Durio",
    "Ferula",
    "Expulso",
    "Expelliarmus",
    "Everte",
    "Evanesce",
    "Epoximise",
    "Entomorphis",
    "Ebublio",
    "Ducklifors",
    "Draconifors",
    "Dissendium",
    "Diminuendo",
    "Deprimo",
    "Densaugeo",
    "Deletrius",
    "Defodio",
    "Crucio",
    "Confundo",
    "Colovaria",
    "Inimicum",
    "Calvario",
    "Bombarda",
    "Brackium",
    "Baubillious",
    "Avis",
    "Ascendio",
    "Avada",
    "Anteoculatia",
    "Anapneo",
    "Alarte",
    "Aguamenti",
    "Accio",
    "Xurio",
    "Yyrgen",
    "Qia",
    "Bou",
    "Xtrio",
    "Jourion",
    "Fhrytthm",
    "Wrainth",
    "Quin",
    "Quattrommat",
    "Houriaugh",
    "Eiindriah",
    "Obelium",
    "Aastrago",
    "Uriandus",
    "Unos",
    "Eigh",
    "Moamiuo",
    "Ambigo",
    "Deighriumpa",
    "Cactio",
    "Xuriphion",
    "Ymprio",
    "Rewendo",
    "Fleighrat",
    "Griumphion",
  ];
}